# distributed training
nodes: 1
gpus: -1 # I recommend always assigning 1 GPU to 1 node
nr: 0 # machine nr. in node (0 -- nodes - 1)
dataparallel: 0 # Use DataParallel instead of DistributedDataParallel
workers: 12
dataset_dir: "/home/nthom/Documents/datasets"

# train options
seed: 3 # sacred handles automatic seeding when passed in the config
batch_size: 128
learning_rate: 0.0001
image_size_h: 224
image_size_w: 224
start_epoch: 0
epochs: 100
dataset: "VGG_Face"
pretrain: True
train: True
val_only: False
test: False

# model options
#resnet: "resnet18"
resnet: "resnet50"

# loss options
optimizer: "Adam"
scheduler: False

# test output options
csv_path: "/home/nthom/Documents/similarity_classifiers/outputs/"

# save options
save: True
save_name: "simclrPretrain_resnet50_VGGDataset_224x224_noTransforms"

# reload options
reload: True
#model_path: "/home/nthom/Documents/similarity_classifiers/checkpoints/"
model_path: "/home/nthom/Documents/simclr/checkpoints/vgg_face/"
#model_file: "epoch=91-Training Loss=3.46329-resnet50_VGGDataset_224x224_SimCLRTransforms.ckpt"
model_file: "epoch=46-Training Loss=0.02167-512-512-0.05-3e-05.ckpt"

# data options
show_batch: False
image_path: "/home/nthom/Documents/datasets/vgg_face_dataset/"
image_dir: "images_cropped_224x224/"
#label_path: "/home/nthom/Documents/similarity_classifiers/misc_code/csvs/vgg_face_224x224_identity_labels.csv"
label_path: "/home/nthom/Documents/similarity_classifiers/misc_code/csvs/vgg_face_224x224_shuffled_identity_labels.csv"
#label_path: "/home/nthom/Documents/similarity_classifiers/misc_code/csvs/vgg_face_224x224_identity_labels_45_classes.csv"
#label_path: "/home/nthom/Documents/similarity_classifiers/misc_code/csvs/vgg_face_224x224_identity_labels_2_classes_shuffled.csv"

train_size: 1014590
val_size: 126824
test_size: 126824
all_size: 1268238
n_classes: 2622

#train_size: 16812
#val_size: 2102
#test_size: 2102
#all_size: 21016
#n_classes: 45

#train_size: 976
#val_size: 0
#test_size: 0
#all_size: 976
#n_classes: 2